name: sandy.wilderman
description: transitional
version: 0.0.1
author: abjjqevk.lknpkuck@eqqhvm2l.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: sandywilderman
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2024-11-22 22:59:28'
pipelines:
  pipelines/Miss_Amal_GreenholtSam_DayoulpayKeitha_Hudson:
    name: Miss_Amal_GreenholtSam_DayoulpayKeitha_Hudson
    description: null
    author: abjjqevk.lknpkuck@eqqhvm2l.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-11-22 22:59:28'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-11-22 22:59:28'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-11-22T22:59:28.082172Z'
  name: plibMaven
  version: 8.6.0-SNAPSHOT
  id: '1354995709'
  createdAt: '2024-11-22T22:59:28.082172Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
